/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting;

import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Luqmaan
 */
public class Head_Boy extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Head_Boy() {
        initComponents();

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String query1 = "Select *from Location;";

            ResultSet rs = stmt.executeQuery(query1);

            if (rs.next() == true) {
                path = rs.getString(1);
            } else {
                int b = JOptionPane.showConfirmDialog(null, "Path to files does not exist \nAdd the path now", "Error", JOptionPane.DEFAULT_OPTION);
                if (b == 0) {
                    JFileChooser browse = new JFileChooser();
                    browse.showSaveDialog(null);
                    File file = browse.getSelectedFile();

                    File ParentFolder = file.getParentFile();

                    path = ParentFolder.getPath().replace("/", "/");

                    stmt.executeUpdate("insert into location values ('" + path + "');");

                    JOptionPane.showMessageDialog(null, "Path Added", "Info", WIDTH);
                }
            }
            con.close();
            stmt.close();
            rs.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String query = "Select UPPER(Name) from headboy order by(name);";

            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                String name = rs.getString(1);

                ls.add(name);
            }
            con.close();
            stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

        try {
            if (ls.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please add the Candidates to Vote", "Error", WIDTH, i);
                
                
            } else {
                name1.setText(ls.get(0).toString());
                name2.setText(ls.get(1).toString());
                name3.setText(ls.get(2).toString());
                name4.setText(ls.get(3).toString());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "\nInsufficient Candidates");
        }

        try {
            ImageIcon headboy1 = new ImageIcon(path + "/" + ls.get(0) + ".jpeg");
            ImageIcon headboy2 = new ImageIcon(path + "/" + ls.get(1) + ".jpeg");
            ImageIcon headboy3 = new ImageIcon(path + "/" + ls.get(2) + ".jpeg");
            ImageIcon headboy4 = new ImageIcon(path + "/" + ls.get(3) + ".jpeg");

            pic1.setText("");
            pic1.setIcon(headboy1);

            pic2.setText("");
            pic2.setIcon(headboy2);

            pic3.setText("");
            pic3.setIcon(headboy3);

            pic4.setText("");
            pic4.setIcon(headboy4);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }
    ArrayList ls = new ArrayList();
    ImageIcon i = new ImageIcon("src/Voting/res/PicsArt_12-25-11.14.35.png");
    String path = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pic3 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pic1 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pic2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pic4 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jPanel4.setMinimumSize(new java.awt.Dimension(280, 280));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        pic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic3.setText("HEAD BOY 3");
        jPanel4.add(pic3);
        pic3.setBounds(13, 14, 254, 252);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 350, 280, 280);

        name1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        name1.setForeground(new java.awt.Color(0, 51, 51));
        name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1.setText("Head Boy 1");
        jPanel1.add(name1);
        name1.setBounds(10, 290, 280, 30);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jPanel2.setMinimumSize(new java.awt.Dimension(280, 280));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(null);

        pic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic1.setText("HEAD BOY 1");
        jPanel2.add(pic1);
        pic1.setBounds(13, 14, 254, 252);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 280, 280);

        name3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        name3.setForeground(new java.awt.Color(0, 51, 51));
        name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name3.setText("Head Boy 3");
        jPanel1.add(name3);
        name3.setBounds(10, 630, 280, 30);

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("BACK TO MENU");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(530, 520, 150, 40);

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("VOTING PAGE");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(530, 470, 150, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HEAD BOY");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 310, 580, 80);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VOTE FOR");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(370, 230, 460, 80);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 60, 130, 150);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jPanel5.setMinimumSize(new java.awt.Dimension(280, 280));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(null);

        pic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic2.setText("HEAD BOY 2");
        jPanel5.add(pic2);
        pic2.setBounds(13, 14, 254, 252);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(890, 10, 280, 280);

        name2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        name2.setForeground(new java.awt.Color(0, 51, 51));
        name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name2.setText("Head Boy 2");
        jPanel1.add(name2);
        name2.setBounds(890, 290, 280, 30);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jPanel3.setMinimumSize(new java.awt.Dimension(280, 280));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(null);

        pic4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic4.setText("HEAD BOY 4");
        jPanel3.add(pic4);
        pic4.setBounds(13, 14, 254, 252);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(890, 350, 280, 280);

        name4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        name4.setForeground(new java.awt.Color(0, 51, 51));
        name4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name4.setText("Head Boy 4");
        jPanel1.add(name4);
        name4.setBounds(890, 630, 280, 30);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HAPPY VOTING");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 600, 310, 50);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ARMY PUBLIC SCHOOL ASC C&C");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 640, 280, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1216, 714));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        String name = name3.getText();

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String query = "update headboy set count = count + 1 where name = '" + name + "';";

            stmt.executeUpdate(query);

            con.close();
            stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }

        JOptionPane.showMessageDialog(this, "Congratulations! \nYou voted for " + name, "CONGRATULATIONS", JOptionPane.WIDTH, i);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        String name = name1.getText();

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String query = "update headboy set count = count + 1 where name = '" + name + "';";

            stmt.executeUpdate(query);

            con.close();
            stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }

        JOptionPane.showMessageDialog(this, "Congratulations! \nYou voted for " + name, "CONGRATULATIONS", JOptionPane.WIDTH, i);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Vote_Frame vote = new Vote_Frame();
        vote.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        String name = name2.getText();

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String query = "update headboy set count = count + 1 where name = '" + name + "';";

            stmt.executeUpdate(query);

            con.close();
            stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }

        JOptionPane.showMessageDialog(this, "Congratulations! \nYou voted for " + name, "CONGRATULATIONS", JOptionPane.WIDTH, i);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        String name = name4.getText();

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/furqaan", "root", "admin");
            Statement stmt = con.createStatement();

            String query = "update headboy set count = count + 1 where name = '" + name + "';";

            stmt.executeUpdate(query);

            con.close();
            stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }

        JOptionPane.showMessageDialog(this, "Congratulations! \nYou voted for " + name, "CONGRATULATIONS", JOptionPane.WIDTH, i);
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Head_Boy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Head_Boy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel pic3;
    private javax.swing.JLabel pic4;
    // End of variables declaration//GEN-END:variables
}
