/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Luqmaan
 */
public class Instructions extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Instructions() {
        initComponents();
        exitL.setIcon(exited);

    }
    
    ImageIcon exited = new ImageIcon("src/res/exit.jpeg");
    ImageIcon entered = new ImageIcon("src/res/exit1.jpeg");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        exitL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 10, 130, 150);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ARMY PUBLIC SCHOOL");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 40, 460, 50);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ASC C&C ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 90, 200, 50);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INSTRUCTIONS MANUAL");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 170, 400, 40);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(65, 65, 65));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("                                                           Welcome to the Army Public School E-voting portal\n\n                                                     Read the following guidelines before using the Application\n\n 1) If you wish to access the Secret Functions of the Applications, you might as well need a \"Secret Code\", which                        corresponds to the SYMBOLS UPON THE DATE OF BIRTH OF THE DEVELOPER.                                                                              (DDMMYY ; Year being - 00 for 2000, 01 for 2001, so on)\n\n 2) On prompted to choose the DEFAULT DIRECTORY, Make sure to Select the Folder which Contains the Pictures of all the\t    Candidates in JPEG FORMAT. \n\n 3) It is significant to be particular about the NAMING AND DIMENSIONS of the pictures of candidates.\n    Two methods for Voting have been designed each with its own resources.\n\n     i) INDIVIDUAL VOTING -\n       Naming - Name to be the same as the name registered in the 'ADD/REMOVE CANDIDATES' Menu\n       Dimensions - 250x250 pixels\n\n    ii) MULTIPLE VOTING - \n       Naming - Name to be the same as the name registered in the 'ADD/REMOVE CANDIDATES' Menu with 'S' before the                                name   (e.g. Name of the Candidate - RAKESH  ; Name of Picture to be - 'SRAKESH')\n       Dimensions - 100x100 pixels \n\n 4) It is most IMPORTANT that you have read and understood all the guidelines.\n\n 5) Stay Tuned and HAPPY VOTING :)\n\n                                                      Please Launch the Application again if launched for the First Time");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(50, 220, 1100, 370);

        exitL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/exit.jpeg"))); // NOI18N
        exitL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitLMouseReleased(evt);
            }
        });
        jPanel1.add(exitL);
        exitL.setBounds(1100, 620, 80, 36);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1216, 714));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitLMouseClicked

    private void exitLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLMouseEntered
        // TODO add your handling code here:
        exitL.setIcon(entered);
    }//GEN-LAST:event_exitLMouseEntered

    private void exitLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLMouseExited
        // TODO add your handling code here:
        exitL.setIcon(exited);
    }//GEN-LAST:event_exitLMouseExited

    private void exitLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLMouseReleased
        if (exitL.getIcon() == entered) {
            try {

                Thread.sleep(500);
                System.exit(0);

            } catch (InterruptedException ex) {
                Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_exitLMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instructions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitL;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
